version: "3.8"
services:
  api:
    build: ./backend
    container_name: backend_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/src/app
      - /node_modules
  myblog:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true

